### ISSUE TITLE
[20280] Failed to execute script '__main__' due to unhandled exception!

### ISSUE THREAD

**Issue by tlover-code** [KovacsGG/pyI2L#4]
I try extract resources.assets but get error. Game is vampire survivors
![image](https://github.com/user-attachments/assets/b869a113-c41d-4cf1-ad9c-5f1bc1b3e870)

**Comment by KovacsGG** [comment]
Thanks for your report!

You need to specify `-f rawCSV` to work with a generic project. Otherwise, the game will likely fail to launch after you apply your patch.

Regardless, you did run into a genuine error. Vampire Survivors appears to be using some format variation that the extractor didn't expect.

I've published a new version that works with VS on my end: https://github.com/KovacsGG/pyI2L/releases/tag/v2.1.2 I've only tested until the main menu though, maybe try switching languages after you applied a few changes. Let me know whether it works correctly now!

You will still need to specify the correct format.

**Comment by tlover-code** [comment]
The new update allows exporting CSV files, but after editing, it cannot be applied.
![image](https://github.com/user-attachments/assets/a924364f-eb65-443f-a914-dd3b8cf7bb65)

**Comment by KovacsGG** [comment]
Please attach the edited CSV. The CSV created by the program is UTF-8 encoded. Make sure your text editor is using that encoding as well.

You are also using the incorrect command. You should export with `pyI2L.exe -f rawCSV` and apply with `pyI2L.exe -a resources.assets.csv -f rawCSV` as I described in my comment above and also in the Usage section of the Readme.

**Comment by tlover-code** [comment]
I have fixed it. Just open the file with Notepad++, set the encoding to UTF-8, save it, and then you can open it with Excel to edit it normally.

**Comment by KovacsGG** [comment]
I've found that Crowdin's free offer works pretty well for these small word count, small team projects. At the very least it doesn't get in your way as much as Excel does.

Did you test launching the game and changing languages? Did it not crash?

**Comment by PhamMinhKha** [comment]
I tried running it with the new language, and it worked well without crashing. Thank you for your project!

**Comment by tlover-code** [comment]
I opened it with the new language, and it worked well without any errors. Thank you for your project.
